### ISSUE TITLE
If a rfc4180 formatted CSV file has lines  that end with a '"' (quotation mark), the parser goes funny

### ISSUE THREAD

**Issue by a-sassmannshausen** [artyom-poptsov/guile-dsv#3]
To reproduce:
- last field quotation with closing new line makes parser explode
  `(dsv-string->scm "test,hello,\"blah\"\r\n" #:format 'rfc4180)`

- last field quotation with now closing new line works fine
  `(dsv-string->scm "test,hello,\"blah\"" #:format 'rfc4180)`

- last field in any non-final line with quotation causes parser errors
 `(dsv-string->scm "test,hello,\"blah\"\r\nincorrect,field,parsing" #:format 'rfc4180)`

I imagine it is an issue to do with end of line parsing…

Best wishes,

Alex

**Comment by artyom-poptsov** [comment]
Fixed in eba042a7ae89f54b2c50c8ff42ced6a349b79971
