### ISSUE TITLE
Distribution in Guix

### ISSUE THREAD

**Issue by a-sassmannshausen** [artyom-poptsov/guile-dsv#5]
Hi Artyom,

I'm keen to get guile-dsv to be part of the Guix package manager.  I would like to propose a patch to it including the changes I've proposed to you in my 2 pull requests.

I'm happy to wait for a bit until you've had a chance to check things out and for us to have this discussion. Alternatively, if you have moved on from this project, I'd be happy to create a recipe from my fork of the project.

What do you think?

Best wishes,

Alex (atheia)

**Comment by artyom-poptsov** [comment]
Hello Alex,

sorry for delays -- I was busy with my day job recently and hadn't enough time to review your patches properly.  I'll take a look on the patches in the next few days.

Thanks!

Artyom.

**Comment by a-sassmannshausen** [comment]
Excellent, no worries!

Alex
