### ISSUE TITLE
When a DSV field in 'rfc4180 format contains escaped quotes followed by a ',' the parser errors out.

### ISSUE THREAD

**Issue by a-sassmannshausen** [artyom-poptsov/guile-dsv#7]
Hi Artyom,

Love the library — use it all the time and it has proved incredibly robust.  I have finally spotted what I think is a bug: when a dsv string or file contains field  which contains an escaped quotation mark section immediately followed by a ',' the parser errors out with:
```
Throw to key `dsv-parser-error' with args `("A field contains unescaped double-quotes" (#<dsv-parser port: #<input: string 7f598e30da80> type: rfc4180 delim: #\, 7f598d41c0c0> "\"test \"\"This contains double parens\"\""))'.

In dsv/rfc4180.scm:
    298:4  0 (fsm-validate #:dsv-list _ #:buffer _ #:field-buffer _ #:record _)
```

The test case to generate the above was:
```
(dsv-string->scm
 "test,\" hello\",\"this is, a comma test\",\"test \"\"This contains double parens\"\" , edurneadu derunin\""
 #:format 'rfc4180)
```

The minimal test case seems to be:
```
;; An rfc4180 row with a single field consisting of a single quotation mark
;; followed immediately by a comma
(dsv-string->scm "\"\"\",\"" #:format 'rfc4180)
;; Adding a single space causes correct parsing:
(dsv-string->scm "\"\"\" ,\"" #:format 'rfc4180)
```

Hope this is a helpful bug report — any idea what might be going on here?

Best wishes,
Alex

**Comment by artyom-poptsov** [comment]
Hello Alex,

first of all, thanks for your report and kind words.

Secondly, [RFC4180](https://tools.ietf.org/html/rfc4180) says that in every double quote that occurs in a field must be escaped with a double quote -- here's a quote about quotes from the quoted standard:
```
   5.  Each field may or may not be enclosed in double quotes (however
       some programs, such as Microsoft Excel, do not use double quotes
       at all).  If fields are not enclosed with double quotes, then
       double quotes may not appear inside the fields.  For example:

       "aaa","bbb","ccc" CRLF
       zzz,yyy,xxx

   6.  Fields containing line breaks (CRLF), double quotes, and commas
       should be enclosed in double-quotes.  For example:

       "aaa","b CRLF
       bb","ccc" CRLF
       zzz,yyy,xxx

   7.  If double-quotes are used to enclose fields, then a double-quote
       appearing inside a field must be escaped by preceding it with
       another double quote.  For example:

       "aaa","b""bb","ccc"
```

Let's check your minimal test case: 
```
"\"\"\",\""
```
Here we see that there are two fields separated by a comma.  Note that the surrounding quotes without backslashes are for the Guile (Scheme) itself as the data we operate is of the type "string".  Remove them:
```
\"\"\",\"
```
If we remove backslashes for clarity, we'll get the following:
```
""","
```
Then, the first field contains three `"`, two of them surround the field as by standard, and one in the middle is the field content.
```
"""
```
So from the parser's perspective it's a quoted field that contains one unquoted quote (that is, it contains `"`) and that's a violation of the aforementioned standard (remember that RFC4180 uses `"` for quoting, not the backslash as in Guile.)  We can add an additional double quote to the first field to make the parser happy (`"\"\"\"\",\""` in Guile), which will produce:
```
"""","
```
but we'll face the same problem as above with the second field as it contains only `"`.

Nevertheless, when I added missing `"` to the second field and test the example, I found what I think is another problem.  To make the things simpler, I used file named `/tmp/input.txt` with the following content as the input for `dsv->scm` procedure (which is the foundation for `dsv-string->scm` anyway):
```
"""",""
```
And tried to parse it in REPL as the follows:
```
scheme@(guile-user)> (begin (write (dsv->scm (open-input-file "/tmp/input.txt") #:format 'rfc4180))
                            (newline))
(("" ""))
```

As you can see, the first field must contain one double quote after parsing, according to the standard -- but contains none instead, which is wrong.

Furthermore, when I changed the input to
```
"she said "hello"",""
```
I got `(("she said \"hello" ""))` as the result, which is also wrong (the parser should have to throw an error.)

From which I conclude that there's an error in the parser for sure, but not exactly the error you reported to. ;-)

**Comment by artyom-poptsov** [comment]
Hello,

could you please check Guile-DSV from the `master` branch?  Does it work for you when the RFC4180 requirements are taken into the account?

Thanks.

**Comment by a-sassmannshausen** [comment]
Heya!

Thanks for taking the time to investigate this is in such depth!

To keep the discussion as on point as possible, I'll only focus on a specific part where I think you misunderstood my test case (apologies for it being somewhat cryptic!):
> […]
>
> ```
> "\"\"\",\""
> ```
> 
> Here we see that there are two fields separated by a comma. Note that the surrounding quotes without backslashes are for the Guile (Scheme) itself as the data we operate is of the type "string". Let's remove them:
> 
> ```
> \"\"\",\"
> ```
> 
> If we remove backslashes for clarity too, we'll get the following:
> 
> ```
> ""","
> ```

Up until here I believe all is correct! :-)

> Then, the first field contains three `"`, two of them surround the field as by standard, and one in the middle is the field content.

This is where I think you misunderstood:  my example case is not 2 fields separated by a comma, but a single field, containing just  *",* .

As per quoted standard:
- It is a single field containing a comma and a double quote, so it needs to be enclosed in double quotes ↦ "","
- Because it contains a double quote, that double quote needs to be escaped ↦ ""","

So to continue your interpretation of the test case:
If we remove the double quote surrounding the single field we get:
```
"",
```
We can then remove the double quote escape of the quote in the field:
```
",
```
Does this make sense?

As a second illustration, which may be easier to read than my cryptic example, consider an example input file called /too-many-damn-double-quotes.csv/:
```
"""field 1 inside quotes"", field one outside quotes",test
```
This is an rfc4180 file that contains one row, with two fields.

The content of the second field is trivial: just *test*.
The first field contains a comma and double quotes, so it must be wrapped in double quotes and the double quotes must be escaped.  It's content is *"field 1 inside quotes", field one outside quotes*.

Using **dsv->scm** on this file errors like my minimal test case does.

Does this help clarify or do you think I'm still not reading the spec right? 

> Nevertheless, when I added missing `"` to the second field and test the example, I found what I think is another problem. To make the things simpler, I used file named `/tmp/input.txt` with the following content as the input for `dsv->scm` procedure (which is the foundation for `dsv-string->scm` anyway):
> 
> ```
> """",""
> ```
> 
> And tried to parse it in REPL as the follows:
> 
> ```
> scheme@(guile-user)> (begin (write (dsv->scm (open-input-file "/tmp/input.txt") #:format 'rfc4180))
>                             (newline))
> (("" ""))
> ```
> 
> As you can see, the first field must contain one double quote after parsing, according to the standard -- but contains none instead, which is wrong.

I agree with this as a separate (perhaps related?) issue.
 
> Furthermore, when I changed the input to
> 
> ```
> "she said "hello"",""
> ```
> 
> I got `(("she said \"hello" ""))` as the result, which is also wrong (the parser should have to throw an error.)

I also agree with this.  The parser interprets your example in exactly the same way as the input
```
"she said ""hello",""
```
Where, as you point out, the first is invalid and should error, and the second is the correct version, which is correctly interpreted.

I will test master now and report back on that.

Cheers,

Alex

**Comment by artyom-poptsov** [comment]
Hello Alex,

> Does this help clarify or do you think I'm still not reading the spec right?

Yes, it does.  You're right about the spec, I just misunderstood you and was too focused on your minimal test.

So I checked the latest version of Guile-DSV with your input:
```
"""field 1 inside quotes"", field one outside quotes",test
```

And got the following:
```
(("\"field 1 inside quotes\", field one outside quotes" "test"))
```

Seems that my last re-write of the parser for RFC4180 did the job anyway, even with a bit of misunderstanding of your report from my side.

What do you think?

> I will test master now and report back on that.

It would be great if you could check the library on your data, indeed.

Thanks,

Artyom.

**Comment by a-sassmannshausen** [comment]
> Hello,
> 
> could you please check Guile-DSV from the `master` branch? Does it work for you when the RFC4180 requirements are taken into the account?
> 
> Thanks.

OK, I've now tested this version and it solves all the problems we discussed in this thread!

I have not done much extensive other testing to catch regressions though!

Thanks for all your help!

Alex
